"""initial schema

Revision ID: 63e28f800897
Revises: 
Create Date: 2026-06-17 00:56:04.310949
"""
from alembic import op
import sqlalchemy as sa


revision = '63e28f800897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('queries_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('connection_meta', sa.JSON(), nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_session_id'), 'data_sources', ['session_id'], unique=False)
    op.create_table('cached_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_source_id', sa.String(length=32), nullable=True),
    sa.Column('question_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('chart_type', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_plans_question_fingerprint'), 'cached_plans', ['question_fingerprint'], unique=False)
    op.create_table('data_dictionaries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_source_id', sa.String(length=32), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_dictionaries_data_source_id'), 'data_dictionaries', ['data_source_id'], unique=False)
    op.create_table('schema_scopes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_source_id', sa.String(length=32), nullable=False),
    sa.Column('tables', sa.JSON(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_scopes_data_source_id'), 'schema_scopes', ['data_source_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('data_source_id', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.String(length=32), nullable=True),
    sa.Column('parent_investigation_id', sa.String(length=32), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=False),
    sa.Column('topology', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('followups_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['parent_investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['schema_scopes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_session_id'), 'investigations', ['session_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_investigation_id'), 'audit_log', ['investigation_id'], unique=False)
    op.create_table('authorized_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('chart_type', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_results_investigation_id'), 'authorized_results', ['investigation_id'], unique=False)
    op.create_table('board_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('primary_factor', sa.String(length=64), nullable=True),
    sa.Column('ranked_factors', sa.JSON(), nullable=False),
    sa.Column('ruled_out', sa.JSON(), nullable=False),
    sa.Column('residual_share', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_decisions_investigation_id'), 'board_decisions', ['investigation_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('investigator_role', sa.String(length=48), nullable=False),
    sa.Column('factor', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('a_value', sa.Float(), nullable=True),
    sa.Column('b_value', sa.Float(), nullable=True),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.Column('explained_share', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_investigation_id'), 'findings', ['investigation_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('suggested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_investigation_id'), 'followups', ['investigation_id'], unique=False)
    op.create_table('governance_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_events_investigation_id'), 'governance_events', ['investigation_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('band_room_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('shared_context', sa.JSON(), nullable=False),
    sa.Column('active_agents', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_investigation_id'), 'rooms', ['investigation_id'], unique=False)
    op.create_table('room_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('room_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender_role', sa.String(length=32), nullable=False),
    sa.Column('target_role', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('safe_summary', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_messages_room_id'), 'room_messages', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_messages_room_id'), table_name='room_messages')
    op.drop_table('room_messages')
    op.drop_index(op.f('ix_rooms_investigation_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_governance_events_investigation_id'), table_name='governance_events')
    op.drop_table('governance_events')
    op.drop_index(op.f('ix_followups_investigation_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_findings_investigation_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_board_decisions_investigation_id'), table_name='board_decisions')
    op.drop_table('board_decisions')
    op.drop_index(op.f('ix_authorized_results_investigation_id'), table_name='authorized_results')
    op.drop_table('authorized_results')
    op.drop_index(op.f('ix_audit_log_investigation_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_session_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_schema_scopes_data_source_id'), table_name='schema_scopes')
    op.drop_table('schema_scopes')
    op.drop_index(op.f('ix_data_dictionaries_data_source_id'), table_name='data_dictionaries')
    op.drop_table('data_dictionaries')
    op.drop_index(op.f('ix_cached_plans_question_fingerprint'), table_name='cached_plans')
    op.drop_table('cached_plans')
    op.drop_index(op.f('ix_data_sources_session_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
